name: Build image

on:
  push:
    branches:
    - '**'

jobs:
  build-image:
    name: Build the default Docker Image
    runs-on: ubuntu-latest
    env:
      DEBIAN_REPO_MIRROR: cdn-aws.deb.debian.org
      INSTALL_METHOD: docker-ha
    steps:
      - name: Show environment
        run: |
          env | sort
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker Image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          TIMESCALE_TSDB_ADMIN: ${{ secrets.TIMESCALEDB_TSDB_ADMIN }}
        run: |
          make build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push to Amazon ECR
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        run: |
          make push-sha