name: Build branch

on:
  push:
    branches:
      - "*/**"
    paths-ignore:
      - ".github/workflows/publish*.yaml"
      - "*.md"

concurrency:
  group: build-branch-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REPOSITORY: timescaledev/timescaledb-ha
  DOCKER_REGISTRY: docker.io
  PG_MAJOR: 16
  ALL_VERSIONS: "true"
  OSS_ONLY: "false"

jobs:
  build-branch:
    name: Build and push branch
    runs-on: [ "self-hosted", "ephemeral", "${{ matrix.runner_type }}" ]

    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, arm64 ]
        include:
          - platform: amd64
            runner_type: x64
          - platform: arm64
            runner_type: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup | Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make build-sha

      - name: Check
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make check-sha

      - name: Publish
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make publish-sha

  publish-combined-manifest:
    name: Publish branch manifest
    needs: [ "build-branch" ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish combined manifest for branch
        run: make publish-combined-sha
