name: Build branch

on:
  push:
    branches:
      - "*/**"
    paths-ignore:
      - ".github/workflows/publish*.yaml"
      - "*.md"

concurrency:
  group: build-branch-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REPOSITORY: timescale/timescaledb-ha
  DOCKER_REGISTRY: docker.io
  PG_MAJOR: 16
  ALL_VERSIONS: "true"
  OSS_ONLY: "false"

jobs:
  build-branch:
    name: Build and push branch
    runs-on: ${{ matrix.runner_type }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ "amd64", "arm64" ]
          - platform: amd64
            runner_type: ubuntu-latest
          - platform: arm64
            runner_type: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup | Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make build-sha

      - name: Check
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make check-sha

      - name: Publish
        env:
          PLATFORM: ${{ matrix.platform }}
        run: make publish-sha
