# To avoid duplicate workflows when only tagging, we have a separate
# workflow file for pushing tags
name: Publish image

on:
  push:
    tags:
    - 'donotuse*'

jobs:
  publish-image:
    name: Publish the Docker Images
    runs-on: ubuntu-latest
    env:
      DEBIAN_REPO_MIRROR: cdn-aws.deb.debian.org
      INSTALL_METHOD: docker-ha
      DOCKER_REGISTRY: docker.io
      TIMESCALE_TSDB_ADMIN: 0.1.1
      TIMESCALE_PROMETHEUS: 0.1.0-beta.1
    steps:
      - name: Publish the Docker Image
        env:
          INSTALL_METHOD: docker-ha
          GITHUB_CICD_TOKEN: ${{ secrets.GITHUB_CICD_TOKEN }}
          DOCKER_REGISTRY: docker.io
          DOCKER_REPOSITORY: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
          DOCKER_TAG_POSTFIX: ${{ env.GITHUB_ACTION }}
          TIMESCALE_TSDB_ADMIN: 0.1.1
          TIMESCALE_PROMETHEUS: 0.1.0-beta.1
        run: |
          echo "${DOCKER_REPOSITORY}"
